### ISSUE TITLE
Dynamically generate LUKS secrets 

### ISSUE THREAD

**Issue by srueg** [cloudscale-ch/csi-cloudscale#10]
Would it be possible to automatically generate a LUKS key and save it in a secret, if no secret was provided with the PVC?

**Comment by davidhalter** [comment]
Since I haven't implemented this, I would like to know from @ferdinandhuebner if he thinks that this would be a good idea or not.

**Comment by ferdinandhuebner** [comment]
The CSI driver is unaware of the CO (Container Orchestrator) it is running on and can't interact with the CO directly. This is by design of the CSI spec to enforce CO agnostic CSI drivers. The LUKS keys are provided by the CO, they aren't read by the driver from the CO.

For Kubernetes or OpenShift, a [dynamic admission controller](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) might be a way to implement auto-generating LUKS secrets. You could e.g. annotate a kubernetes PVC with something like `cloudscale.ch/auto-generate-luks-key: "true"` and the admission controller would create LUKS keys for such PVCs before the PVC is admitted to kubernetes. This would be a project or tool independent of the CSI driver and would need to be deployed separately.

Please note that auto-generating LUKS secrets would introduce a risk of losing LUKS keys and access to the encrypted filesystem should you somehow lose the kubernetes secret. This could happen if the Kubernetes etcd storage itself is lost or the Kubernetes secret deleted by accident.

Another alternative would be to not rely on the CO to supply the LUKS key. The driver could be integrated with a system for secret storage like HashiCorp vault or a HSM. A Kubernetes cluster that would store LUKS secrets would be another possible system.

I actually decided against an external secret storage mechanism when LUKS support was implemented last year, because it would introduce additional complexity and dependencies.
At least on Kubernetes (I don't know about other COs like Cloud Foundry or Mesos), the LUKS key can be stored in and injected by the CO with the [StorageClass Secrets feature of the Kubernetes CSI provisioner](https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html#storageclass-secrets) that we're currently using.

I think an admission controller would be the least invasive solution. The external secret storage mechanism would make sense if you don't want to store the encryption key in the Kubernetes cluster where the CSI driver is running on.
